### ISSUE TITLE
.idea directory should not be added to git.

### ISSUE THREAD

**Issue by bdsumon4u** [asif17r/Django-Rest-Api#1]
Editor-specific folders such as `.idea` should not be added to git.
You can add a `.editorconfig` file, but adding the `.idea` directory to git is a very bad practice.

**Comment by asif17r** [comment]
F**k you

> Editor-specific folders such as `.idea` should not be added to git. You can add a `.editorconfig` file, but adding the `.idea` directory to git is a very bad practice.

Main rules manta nahi, main rules banata hu..
